default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: postgres

development:
  <<: *default
  database: awestacks_development

test:
  <<: *default
  database: awestacks_test

production:
  <<: *default
  host: ec2-54-235-86-226.compute-1.amazonaws.com
  database: dbdbqdlmslt4km
  username: uruksehodxnnic
  password: 0cca8ce2eb26a5b60047ae1e2ad5f78f567d831f28ffd86f5150d596156830db
